#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V

# bspc config border_width         2
bspc config border_width         3
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color       "#4c2f54" 
bspc config active_border_color	      "#1e1e1e" 
bspc config focused_border_color	  "#c793db" 
bspc config presel_feedback_color	  "#5e81ac" 
bspc config urgent_border_color 	  "#dd2727"
bspc config focus_follows_pointer true

xsetroot -cursor_name left_ptr &

feh --bg-fill ~/My_Linux_config/wallpaper/street.png

#Autostart applications
sxhkd &
# picom --animations --animation-for-open-window fly-in -b --experimental-backends &
picom --config ~/.config/picom/picom.conf &
# dunst &
# polybar &
# ~/.config/polybar/launch.sh
# polybar main &
sh ~/.config/polybar/launch.sh &

